# Default values for containerized-microservices-pipeline-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: login-app
env: production

app:
  replicaCount: 2
  image:
    repository: acrmicrok8eastus.azurecr.io # ACR Login Server
    imageName: containerized-microservices-pipeline-app
    tag: "1.0.1" # override on cli using --set app.image.tag=<version>
    pullPolicy: Always
  port:
    name: http
    containerPort: 80
    protocol: TCP
  imagePullSecrets: acr-credentials # Name of ACR Credential Secret

service:
  type: ClusterIP
  port: 80
  targetPort: 80