kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: "{{ .Values.appName }}-{{ .Values.env }}"
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        env: {{ .Values.env }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.app.image.repository }}/{{ .Values.app.image.imageName }}:{{ .Values.app.image.tag }}
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
          - name: {{ .Values.app.port.name }}
            containerPort: {{ .Values.app.port.containerPort }}
            protocol: {{ .Values.app.port.protocol }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
      - name: {{ .Values.app.imagePullSecrets }}