apiVersion: v1
kind: Service
metadata:
  name: {{ template "containerized-microservices-pipeline-app.fullname" . }}-service
  labels:
    app: {{ template "containerized-microservices-pipeline-app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "containerized-microservices-pipeline-app.name" . }}
    release: {{ .Release.Name }}
