{{ if eq .Values.app.image.tag "canary" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "containerized-microservices-pipeline-app.basename" . }}-service
  labels:
    app: {{ template "containerized-microservices-pipeline-app.basename" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "containerized-microservices-pipeline-app.basename" . }}
{{- end }}